//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd", IsNullable = false)]
public partial class OfferCreate
{

    private string eANField;

    private string conditionField;

    private decimal priceField;

    private string deliveryCodeField;

    private int quantityInStockField;

    private bool publishField;

    private string referenceCodeField;

    private string descriptionField;

    /// <remarks/>
    public string EAN
    {
        get
        {
            return this.eANField;
        }
        set
        {
            this.eANField = value;
        }
    }

    /// <remarks/>
    public string Condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }

    /// <remarks/>
    public decimal Price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    public string DeliveryCode
    {
        get
        {
            return this.deliveryCodeField;
        }
        set
        {
            this.deliveryCodeField = value;
        }
    }

    /// <remarks/>
    public int QuantityInStock
    {
        get
        {
            return this.quantityInStockField;
        }
        set
        {
            this.quantityInStockField = value;
        }
    }

    /// <remarks/>
    public bool Publish
    {
        get
        {
            return this.publishField;
        }
        set
        {
            this.publishField = value;
        }
    }

    /// <remarks/>
    public string ReferenceCode
    {
        get
        {
            return this.referenceCodeField;
        }
        set
        {
            this.referenceCodeField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd", IsNullable = false)]
public partial class OfferUpdate
{

    private decimal priceField;

    private string deliveryCodeField;

    private bool publishField;

    private string referenceCodeField;

    private string descriptionField;

    /// <remarks/>
    public decimal Price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    public string DeliveryCode
    {
        get
        {
            return this.deliveryCodeField;
        }
        set
        {
            this.deliveryCodeField = value;
        }
    }

    /// <remarks/>
    public bool Publish
    {
        get
        {
            return this.publishField;
        }
        set
        {
            this.publishField = value;
        }
    }

    /// <remarks/>
    public string ReferenceCode
    {
        get
        {
            return this.referenceCodeField;
        }
        set
        {
            this.referenceCodeField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd", IsNullable = false)]
public partial class StockUpdate
{

    private int quantityInStockField;

    /// <remarks/>
    public int QuantityInStock
    {
        get
        {
            return this.quantityInStockField;
        }
        set
        {
            this.quantityInStockField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd", IsNullable = false)]
public partial class OfferFile
{

    private string urlField;

    /// <remarks/>
    public string Url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://plazaapi.bol.com/offers/xsd/api-1.0.xsd", IsNullable = false)]
public partial class ServiceError
{

    private int errorCodeField;

    private string errorMessageField;

    /// <remarks/>
    public int ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }

    /// <remarks/>
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}
